baseURL = "/"
title = "–ü–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

[params]
  description = "–ö–µ–π—Å—ã –∏ –ø–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
  author_name = "–†—É—Å–ª–∞–Ω"
  author_surname = "–®–∞—Ä–∏–ø–æ–≤"
  author_grade = "—Å—Ç–∞—Ä—à–∏–π –ø—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
  author_city = "–°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥"
  author_intro = "üëãüèª, —è –ø—Ä–æ–µ–∫—Ç–∏—Ä—É—é —Ü–∏—Ñ—Ä–æ–≤—ã–µ –ø—Ä–æ–¥—É–∫—Ç—ã —Å —É—á–µ—Ç–æ–º –±–æ–ª–∏ –∏ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –±–∏–∑–Ω–µ—Å–∞."
  author_image = "/images/author.jpg"
  author_email = "ruslanshgd@gmail.com"
  author_telegram = "https://t.me/rsgdru"
  author_linkedin = "https://www.linkedin.com/in/ruslan-sharipov/"
  author_dribbble = ""
  author_behance = "https://www.behance.net/ruslansh"
  author_cv = "https://drive.google.com/file/d/17-WqbIrYUbzBeoUAbawsEdOcYIFguWre/view?usp=sharing"

  [params.education]

  [[params.education.universities]]
    name = "–°–ü–±–ì–£–ü–¢–î"
    year = "2016"
    speciality = "–°–ø–µ—Ü–∏–∞–ª–∏—Å—Ç –≤ –≥—Ä–∞—Ñ. –¥–∏–∑–∞–π–Ω–µ."

  [params.career]

  [[params.career.items]]
    company = "Click-Click"
    role = "–í–µ–±-–¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2015 - 2016"
    end = "2016"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å –±—Ä–∞—É–∑–µ—Ä–∞ Orbitum –∏ —Å–º–µ–∂–Ω—ã–µ –ø—Ä–æ–µ–∫—Ç—ã –∫–æ–º–ø–∞–Ω–∏–∏."

  [[params.career.items]]
    company = "MPMG"
    role = "–í–µ–±-–¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2016"
    end = "2017"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª –æ–¥–∏–Ω –∫—Ä—É–ø–Ω—ã–π –ø—Ä–æ–µ–∫—Ç: —Å–∞–π—Ç-–∞–≥—Ä–µ–≥–∞—Ç–æ—Ä —Ä–∞–∑–ª–∏—á–Ω—ã—Ö –ø—Ä–æ–≥—Ä–∞–º–º –ª–æ—è–ª—å–Ω–æ—Å—Ç–∏."

  [[params.career.items]]
    company = "–ö—É–ø–∏–±–∏–ª–µ—Ç"
    role = "–ü—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2017"
    end = "2018"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª –≤–µ–±- –∏ –º–æ–±–∏–ª–∫–∏: –æ—Ç–∑—ã–≤—á–∏–≤–∞—è –≤–µ—Ä—Å–∏—è —Å–∞–π—Ç–∞, —É–ª—É—á—à–∞–ª —Å—Ü–µ–Ω–∞—Ä–∏–∏ –Ω–∞ –º–æ–±–∏–ª–∫–∞—Ö."

  [[params.career.items]]
    company = "Siemens"
    role = "UX/UI –¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2018"
    end = "2022"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª —Å–ª–æ–∂–Ω—ã–µ –∏ –ø—Ä–æ—Å—Ç—ã–µ –≤–µ–±- –∏ –º–æ–±–∏–ª—å–Ω—ã–µ –ø—Ä–∏–ª–æ–∂–µ–Ω–∏—è."

  [[params.career.items]]
    company = "–ú–æ–π–û—Ñ–∏—Å"
    role = "–°—Ç–∞—Ä—à–∏–π –ø—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2023"
    end = "2023"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª –Ω–∞—Å—Ç–æ–ª—å–Ω—ã–µ —Ä–µ–¥–∞–∫—Ç–æ—Ä—ã: —Ç–µ–∫—Å—Ç, —Ç–∞–±–ª–∏—Ü—ã, –ø—Ä–µ–∑–µ–Ω—Ç–∞—Ü–∏–∏."

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # optional later: tag = "tags"
